"""Build: the one writer of jobs.json and the generated views.

    py engine/build.py            ingest new inbox.csv rows, regenerate leaderboard.md and pipeline.md, rewrite the
                                  Status/Verdict header lines of job files, fold **Human path:** lines into
                                  human_path (engine/human_path.py), pin new office addresses (engine/office.py),
                                  pull people, opportunities and meetings from Notion (engine/notion_sync.py), then push the board
                                  to Supabase
    py engine/build.py --no-push  skip the Supabase push and geocoder network calls (faster while editing markdown views)

Single-writer rule: the cloud radar appends to inbox.csv (and may fill score,why); this script owns everything
else in jobs/ that is generated. Job markdown files stay hand-written except the two header lines rewritten here.
Idempotent: a second run right after the first changes nothing.
"""
import contextlib
import csv
import io
import re
import sys
from datetime import date

from common import (load_config, paths, load_jobs, save_jobs, new_record, canonical_url, job_id,
                    find_by_url, merge_duplicates, STAGE_TO_STATUS)
from human_path import fold_all as fold_human_paths
from office import geocode_pending
from posting_check import find_repost, note_repost

GENERATED = "<!-- generated by job-search-agent engine/build.py from jobs/jobs.json; do not hand-edit -->"


# ---------- ingest ----------

def ingest_inbox(p, data):
    """New rows in inbox.csv become records. Existing records are never overwritten from the CSV,
    except a null score gets the radar's score when the CSV carries one. A row whose title and company match a
    record closed because its ad went away is a repost (the owner, 2026-10-07): it joins that record through
    posting_check.note_repost (alias, posting dates, the REPOSTED line in the morning post) and mints no card."""
    if not p.inbox_csv.exists():
        return 0, 0
    added = reposted = 0
    with p.inbox_csv.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            score = int(row["score"]) if (row.get("score") or "").strip().isdigit() else None
            j = find_by_url(data, row["url"])
            if j:
                if j.get("score") is None and score is not None:
                    j["score"], j["score_kind"], j["why"] = score, "title", row.get("why") or j.get("why")
                continue
            old = find_repost(data, row["title"], row["company"])
            if old:
                note_repost(old, row["url"], date.today())
                reposted += 1
                continue
            data["jobs"].append(new_record(
                id=job_id(row["url"]), url=canonical_url(row["url"]), title=row["title"].strip(),
                company=row["company"].strip(), company_key=row["company"].strip(),
                location=row["location"].strip() or None, source=f"{row['board']}:{row['alert_name']}",
                date_first_seen=row["date_first_seen"], score=score, score_kind=("title" if score is not None else None),
                why=(row.get("why") or None)))
            added += 1
    return added, reposted


# ---------- derived text ----------

def short_date(iso):
    if not iso:
        return ""
    y, m, d = iso.split("-")
    return f"{int(m)}/{int(d)}"


def status_text(j):
    v = j.get("verdict")
    if v == "pursue":
        s = f"Pursue (the owner {short_date(j.get('verdict_date'))})"
        st = j.get("stage")
        if st and st != "shortlist":
            s += f"; {st}" + (f", {j['outcome']}" if j.get("outcome") else "")
        return s
    if v == "maybe":
        s = f"Maybe (the owner {short_date(j.get('verdict_date'))})"
        return s + (f": {j['status_note']}" if j.get("status_note") else "")
    if v == "pass":
        s = f"Pass (the owner {short_date(j.get('verdict_date'))})"
        return s + (f": {j['status_note']}" if j.get("status_note") else "")
    if ":" in (j.get("source") or ""):
        return f"New via radar {j.get('date_first_seen') or ''}".strip()
    return "Not yet reviewed"


def source_text(j):
    src = j.get("source") or ""
    if j.get("job_file"):
        return f"[[{j['job_file'].split('/', 1)[1]}]]"
    if ":" in src:
        board, alert = src.split(":", 1)
        return f"{board} alert {short_date(j.get('date_first_seen'))}".strip()
    return src


def on_board(j, min_score):
    return (j.get("score") or 0) >= min_score and not j.get("excluded") and j.get("verdict") != "pass"


# ---------- views ----------

def render_leaderboard(p, data, min_score):
    rows = [j for j in data["jobs"] if on_board(j, min_score)]
    rows.sort(key=lambda j: (0 if j.get("flag") else 1, -(j.get("score") or 0), j.get("date_first_seen") or "", j["id"]))
    n_un = sum(1 for j in rows if not j.get("verdict"))
    n_p = sum(1 for j in rows if j.get("verdict") == "pursue")
    n_m = sum(1 for j in rows if j.get("verdict") == "maybe")
    out = [GENERATED, "# Role Leaderboard", "",
           f"Generated {data['asof']} from `jobs.json` ({len(data['jobs'])} postings tracked). Rows: rubric score {min_score}+ that the owner has not passed on, "
           "flags (⚑, set by the owner) first, then score. Scores marked title-level are provisional until the weekly deep pass reads the posting. "
           "Passed and excluded roles stay in jobs.json (with the owner's reasons, the rubric's training data) and are listed at the bottom.", "",
           f"On the board: {len(rows)} ({n_p} Pursue, {n_m} Maybe, {n_un} not yet reviewed). Rubric and hard exclusions: [[rubric]].", "",
           "| Rank | Role | Company | Score | Flag | Location | Status | Source |",
           "|------|------|---------|-------|------|----------|--------|--------|"]
    for i, j in enumerate(rows, 1):
        sc = f"{j['score']}" + ("" if j.get("score_kind") == "deep" else " (title)")
        out.append(f"| {i} | {j['title']} | {j['company']} | {sc} | {'⚑' if j.get('flag') else ''} | {j.get('location') or ''} | {status_text(j)} | {source_text(j)} |")
    out += ["", "Sub-7 scores and everything else the radar collected live in `jobs.json` and `inbox.csv`.", "",
            "## Passed", ""]
    passed = [j for j in data["jobs"] if j.get("verdict") == "pass" and not j.get("excluded")]
    passed.sort(key=lambda j: (-(j.get("score") or 0), j["title"]))
    for j in passed:
        out.append(f"- {j.get('verdict_date') or ''}: {j['title']}, {j['company']} (scored {j.get('score')}). {j.get('status_note') or ''}".rstrip())
    out += ["", "## Excluded or closed", ""]
    exc = [j for j in data["jobs"] if j.get("excluded")]
    exc.sort(key=lambda j: (-(j.get("score") or 0), j["title"]))
    for j in exc:
        out.append(f"- {j.get('verdict_date') or ''}: {j['title']}, {j['company']} (scored {j.get('score')}). {j['excluded']}.")
    p.leaderboard.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    return len(rows)


def render_pipeline(p, data):
    rows = [j for j in data["jobs"] if j.get("job_file") or (j.get("source") == "hand")]

    def order(j):
        v = j.get("verdict")
        return (0 if v == "pursue" else 1 if v == "maybe" else 2 if v is None else 3, -(j.get("score") or 0), j["title"])
    rows.sort(key=order)
    out = [GENERATED, "# Pipeline", "",
           f"Generated {data['asof']} from `jobs.json`: every role with a job file, plus hand-tracked threads. "
           "Stage moves happen on the dashboard (or by telling Claude) and land here on the next build. "
           "Maybe roles without a file live on [[../jobs/leaderboard]] only.", "",
           "| Company | Role | Status | Next Step | Date |", "|---------|------|--------|-----------|------|"]
    for j in rows:
        comp = f"[[{j['company_file']}]]" if j.get("company_file") else j["company"]
        role = (f"[[{j['job_file']}]] " if j.get("job_file") else "") + j["title"]
        v = j.get("verdict")
        if v == "pursue":
            st = STAGE_TO_STATUS.get(j.get("stage") or "shortlist", "Shortlist")
            status = f"{st}, Pursue"
            if j.get("stage") == "closed":
                status = "Closed" + (f": {j['outcome']}" if j.get("outcome") else "")
        elif v == "maybe":
            status = "Researching, Maybe"
        elif v == "pass":
            status = f"Closed: passed {j.get('verdict_date') or ''}" + (f", {j['status_note']}" if j.get("status_note") else "")
        else:
            status = "Researching"
        nxt = j.get("next_step") or ("None" if v == "pass" else "")
        dt = j.get("next_step_date") or j.get("stage_date") or j.get("verdict_date") or ""
        out.append(f"| {comp} | {role} | {status} | {nxt} | {dt} |")
    p.pipeline.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    return len(rows)


def sync_job_files(p, data):
    """Rewrite only the **Status:** and **Verdict:** header lines of each linked job file."""
    n = 0
    for j in data["jobs"]:
        if not j.get("job_file"):
            continue
        f = p.vault / (j["job_file"] + ".md")
        if not f.exists():
            continue
        txt = f.read_text(encoding="utf-8")
        v = j.get("verdict")
        if v == "pursue":
            status = STAGE_TO_STATUS.get(j.get("stage") or "shortlist", "Shortlist")
            if j.get("stage") == "closed":
                status = "Closed" + (f": {j['outcome']} {j.get('stage_date') or ''}".rstrip() if j.get("outcome") else "")
        elif v == "pass":
            status = f"Closed: the owner passed {j.get('verdict_date') or ''}" + (f" ({j['status_note']})" if j.get("status_note") else "")
        elif v == "maybe":
            status = "Researching (Maybe)"
        else:
            status = None
        new = txt
        if status:
            new = re.sub(r"^\*\*Status:\*\*.*$", f"**Status:** {status}", new, count=1, flags=re.M)
        if v:
            cal = f"; score feels {j['calibration'].lower()}" if j.get("calibration") else ""
            verdict = f"**Verdict:** {v.capitalize()} (the owner, {j.get('verdict_date') or ''}{cal})"
            if re.search(r"^\*\*Verdict:\*\*", new, re.M):
                new = re.sub(r"^\*\*Verdict:\*\*.*$", verdict, new, count=1, flags=re.M)
            else:
                new = re.sub(r"^(\*\*Status:\*\*.*)$", r"\1\n" + verdict, new, count=1, flags=re.M)
        if new != txt:
            f.write_text(new, encoding="utf-8", newline="\n")
            n += 1
    return n


def refresh_pages(cfg):
    """Keep the Notion Opportunity and Company page bodies in step with the record. Never breaks the build:
    a Notion hiccup leaves the pages as they were."""
    import argparse
    try:
        import notion_companies
        import notion_opps
        a = argparse.Namespace(dry_run=False, all=False)
        with contextlib.redirect_stdout(io.StringIO()) as out:
            notion_opps.fill(a)
            notion_companies.fill(a)
        lines = [l for l in out.getvalue().splitlines() if l.startswith("filled")]
        return "notion pages " + " and ".join(l.replace("filled ", "") for l in lines) if lines else "notion pages"
    except (SystemExit, OSError, ValueError, KeyError) as e:
        return f"notion pages not refreshed ({e})"


def main():
    cfg = load_config()
    p = paths(cfg)
    min_score = int(cfg.get("min_score", 7))
    data = load_jobs(p)
    if not data["jobs"]:
        raise SystemExit("jobs.json is empty; run migrate_once.py first")
    added, reposted = ingest_inbox(p, data)
    folded = merge_duplicates(data)
    n_paths = len(fold_human_paths(p, data))
    pinned, _ = geocode_pending(p, data, network="--no-push" not in sys.argv)
    for j in data["jobs"]:
        j.setdefault("company_key", j["company"])
        if j.get("verdict") == "pursue" and not j.get("stage"):
            j["stage"], j["stage_date"] = "shortlist", j.get("verdict_date")
    data["asof"] = date.today().isoformat()
    save_jobs(p, data)
    n_board = render_leaderboard(p, data, min_score)
    n_pipe = render_pipeline(p, data)
    n_files = sync_job_files(p, data)
    msg = f"jobs.json {len(data['jobs'])} records (+{added} from inbox.csv, {reposted} reposts, {folded} folded, {n_paths} human paths, {len(pinned)} offices pinned); leaderboard {n_board} rows; pipeline {n_pipe} rows; {n_files} job files touched"
    if "--no-push" not in sys.argv:
        from push_board import push
        from notion_sync import refresh as refresh_notion
        notion_msg = refresh_notion(cfg, p)[1]
        pages_msg = refresh_pages(cfg)
        msg += f"; {notion_msg}; {pages_msg}"
        # The banner reads these: a failed pull means the people and opportunities are from the last good one.
        health = {"notion": {"ok": None if "skipped" in notion_msg else "failed" not in notion_msg, "detail": notion_msg},
                  "pages": {"ok": "not refreshed" not in pages_msg, "detail": pages_msg}}
        try:
            msg += f"; {push(cfg, p, data, health)}"
        except (SystemExit, OSError) as e:  # Supabase unreachable: the markdown views are already written
            print(msg)
            raise SystemExit(f"board push failed: {e}")
    print(msg)


if __name__ == "__main__":
    main()
